name: "bleachwrt"
version: "latest"
slug: "bleachwrt"
description: "bleachwrthaos - 提供旁路由管理功能，集成WEB管理界面"
url: "https://github.com/gky008/hassio-addons/main/bleachwrt"
arch:
  - amd64
startup: application
boot: manual
init: false
hassio_network: false
ports_description:
  80/tcp: "WEB服务端口"
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_TIME
  - SYS_NICE
  - SYS_MODULE
  - NET_RAW
webui: "http://[HOST]:[PORT:80]/"
watchdog: "http://[HOST]:[PORT:80]/"
apparmor: false
  log_level: list(info|debug)
image: gky008/bleachwrthaos
