{
  "name": "Sherpa-OnnxAsr",
  "version": "paraformer-2024-7-5",
  "slug": "sherpa-onnx-asr",
  "description": "本地离线语音模型，占用1GB",
  "url": "https://github.com/yaming116",
  "arch": ["amd64", "aarch64"],
  "startup": "application",
  "boot": "auto",
  "init": false,
  "image": "yaming116/sherpa-onnx-asr",
  "ports": {
    "5001/tcp": 5001
  },
  "ports_description": {
    "5001/tcp": "ASR Web interface"
  },
  "map": {
    "config": {
      "path": "/data",
      "readonly": false
    }
  },
  "environment": {},
  "options": {
    "language": "zh-CN"
  },
  "schema": {
    "language": "str"
  },
  "ingress": true,
}
