name: Fusion-RSS
version: "0.8.8"
slug: fusion
description: 轻量级的、自托管支持 Phone 友好型 RSS 聚合器和阅读器
url: https://github.com/0x2E/fusion
arch:
  - amd64
  - aarch64
startup: application
init: false
image: rook1e404/fusion
network_mode: host
webui: "http://[HOST]:[PORT:7077]"
ports:
  "8080/tcp": 7077
ports_description:
  "7077/tcp": "RSS Web interface"
map:
  config:
    path: /data
    readonly: false
volumes:
  - ./data:/data
options:
  host: "0.0.0.0"
  port: 7077
  password: "fusion"
  db: "fusion.db"
  secure_cookie: false
  tls_cert: ""
  tls_key: ""
schema:
  host: str
  port: int
  password: str
  db: str
  secure_cookie: bool
  tls_cert: str
  tls_key: str
environment:
  HOST: !secret host
  PORT: !secret port
  PASSWORD: !secret password
  DB: !secret db
  SECURE_COOKIE: !secret secure_cookie
  TLS_CERT: !secret tls_cert
  TLS_KEY: !secret tls_key
ingress: false
