name: Fusion-RSS
version: "0.8.8"
slug: fusion
description: 轻量级的、自托管支持 Phone 友好型 RSS 聚合器和阅读器
url: https://github.com/0x2E/fusion
arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: false
image: rook1e404/fusion
webui: http://[HOST]:[PORT:7077]
ports:
  "7077/tcp": 8080
ports_description:
  "7077/tcp": RSS Web interface
map:
  config:
    path: /data
    readonly: false
options:
  password: rss123456
schema:
  password: str
environment:
  PASSWORD: rss123456
ingress: true
