name: Fusion-RSS
version: "0.8.8"
slug: fusion
description: 轻量级的、自托管支持 Phone 友好型 RSS 聚合器和阅读器
url: https://github.com/0x2E/fusion
arch:
  - amd64
  - aarch64
startup: application
init: false
image: rook1e404/fusion
network_mode: host
webui: "http://[HOST]:[PORT:8080]"
map:
  config:
    path: /data
    readonly: false
volumes:
  - ./data:/data
options:
  password: "rss123456"
  secure_cookie: false
schema:
  password: str
  secure_cookie: bool
environment:
  PASSWORD: rss123456
  DB: fusion.db
ingress: false
