name: LocalGPT server
version: "latest"
slug: localgpt_server
description: 本地化接口
url: "https://github.com/knoop7"
arch:
  - aarch64
  - amd64
init: false
ingress: true
host_network: true  
panel_icon: "mdi:head-dots-horizontal"
panel_title: "localGPT-server"
ports:
  "4567/tcp": 8080
schema:
  proxy_url: str
image: "ghcr.io/aurora-develop/duck2api"
environment:
  PROXY_URL: "${proxy_url}"
