name: LocalGPT server
version: "latest"
slug: localgpt_server
description: 本地化GPT接口
url: "https://github.com/knoop7"
arch:
  - aarch64
  - amd64
init: false
network_mode: bridge
webui: "http://[HOST]:[PORT:4567]/web"
ports:
  "8080/tcp": 4567
ports_description:
  "4567/tcp": "GPT Web interface"
schema:
  proxy_url:
    type: str
    required: true
    default: "http://192.168.0.185:8899"
image: "ghcr.io/aurora-develop/duck2api"
environment:
  PROXY_URL: "!proxy_url"
