name: LocalGPT server
version: "latest"
slug: localgpt_server
description: 本地化GPT接口
url: "https://github.com/knoop7"
arch:
  - aarch64
  - amd64
init: true
network_mode: bridge
webui: "http://[HOST]:[PORT:4567]/web"
ports:
  "8080/tcp": 4567
ports_description:
  "4567/tcp": "GPT Web interface"
schema:
  proxy_url: str
image: "ghcr.io/aurora-develop/duck2api"
options:
  proxy_url: "http://192.168.0.185:8899"
init_commands:
  - ["/bin/bash", "/run.sh"]
