name: LocalGPT server
version: "20240825"
slug: localgpt_server
description: 本地化GPT接口
url: "https://github.com/knoop7"
arch:
  - aarch64
  - amd64
init: false
network_mode: bridge
webui: "http://[HOST]:[PORT:4567]/web"
ports:
  "4567/tcp": 4567
ports_description:
  "4567/tcp": "GPT Web interface"
schema:
  proxy_url:
    type: str
    description: "代理服务器URL"
    required: false
  server_host:
    type: str
    description: "服务器主机"
    required: false
  server_port:
    type: str
    description: "服务器端口"
    required: false
  tls_cert:
    type: str
    description: "TLS 证书路径"
    required: false
  tls_key:
    type: str
    description: "TLS 密钥路径"
    required: false
options:
  proxy_url: ""
  server_host: ""
  server_port: ""
  tls_cert: ""
  tls_key: ""
map:
  - "data:/data/options.json"
image: "ghcr.io/knoop7/gptapi:20240825"
