name: LocalGPT server
version: "2024-8-26"
slug: localgpt_server
description: 本地化GPT接口
url: "https://github.com/knoop7"
arch:
  - aarch64
  - amd64
init: false
network_mode: bridge
webui: "http://[HOST]:[PORT:4567]/web"
ports:
  "8080/tcp": 4567
ports_description:
  "4567/tcp": "GPT Web interface"
schema:
  proxy_url: str?
options:
  proxy_url: "http://192.168.0.185:8899"
map:
  - config:rw
image: "yaming116/gptapi"
